#ifndef LMTEMPSENSORSTABLE_H
#define LMTEMPSENSORSTABLE_H

void init_lmTempSensorsTable(void);
void deinit_lmTempSensorsTable();
void initialize_table_lmTempSensorsTable(void);
Netsnmp_Node_Handler lmTempSensorsTable_handler;
Netsnmp_First_Data_Point lmTempSensorsTable_get_first_data_point;
Netsnmp_Next_Data_Point lmTempSensorsTable_get_next_data_point;

#define COLUMN_LMTEMPSENSORSINDEX 1
#define COLUMN_LMTEMPSENSORSDEVICE 2
#define COLUMN_LMTEMPSENSORSVALUE 3

#endif
